ALTER TABLE `Venta`
  ADD COLUMN `isv` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  ADD COLUMN `tipoDocumento` ENUM('RECIBO', 'FACTURA') NOT NULL DEFAULT 'RECIBO',
  ADD COLUMN `conEnvio` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `envio` DECIMAL(10, 2) NOT NULL DEFAULT 0.00;
