-- Notas module baseline (idempotent safeguards)
CREATE TABLE IF NOT EXISTS `Nota` (
  `id` VARCHAR(191) NOT NULL,
  `clienteId` VARCHAR(191) NOT NULL,
  `usuarioId` VARCHAR(36) NOT NULL,
  `contenido` LONGTEXT NOT NULL,
  `evidencia` LONGTEXT NULL,
  `createAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updateAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `Nota`
  ADD COLUMN IF NOT EXISTS `clienteId` VARCHAR(191) NOT NULL,
  ADD COLUMN IF NOT EXISTS `usuarioId` VARCHAR(36) NOT NULL,
  ADD COLUMN IF NOT EXISTS `contenido` LONGTEXT NOT NULL,
  ADD COLUMN IF NOT EXISTS `evidencia` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `createAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `updateAt` DATETIME(3) NOT NULL;

CREATE INDEX IF NOT EXISTS `IX_Nota_clienteId` ON `Nota`(`clienteId`);
CREATE INDEX IF NOT EXISTS `IX_Nota_usuarioId` ON `Nota`(`usuarioId`);

ALTER TABLE `Nota`
  ADD CONSTRAINT `Nota_clienteId_fkey` FOREIGN KEY (`clienteId`) REFERENCES `Cliente`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `Nota_usuarioId_fkey` FOREIGN KEY (`usuarioId`) REFERENCES `Usuarios`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
